# Changes here will be overwritten by Copier
_commit: v2.0.8
_src_path: https://github.com/phil65/copier-phil65.git
author_email: philipptemminghoff@googlemail.com
author_fullname: Philipp Temminghoff
author_username: phil65
copyright_date: '2025'
copyright_holder: Philipp Temminghoff
copyright_holder_email: philipptemminghoff@googlemail.com
libraries_use_pydantic: false
libraries_use_qt: false
project_description: CLI project manager for batch operations
project_name: RepoBatch
python_minimum_version: '3.13'
python_package_command_line_name: repobatch
python_package_distribution_name: repobatch
python_package_import_name: repobatch
repository_name: repobatch
repository_namespace: phil65
repository_provider: github.com

